package views;

import javax.swing.ButtonGroup;
import models.Admin;
import models.Bird;
import models.DBManager;
import models.Fish;

/**
 *
 * @author 30257320
 */
public class AddAnimal extends javax.swing.JFrame {

    private Admin loggedInAdmin;
    private ButtonGroup bg;
    /**
     * Creates new form AddAnimal
     */
    public AddAnimal(Admin admin) {
        loggedInAdmin = admin;
        initComponents();
        
        //group radio buttons so only 1 can be selected
        bg = new ButtonGroup();
        bg.add(rdnBird);
        bg.add(rdnFish);
        
        lblAdditionalProperty.setVisible(false);
        additionalTxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdnBird = new javax.swing.JRadioButton();
        rdnFish = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        animalNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        animalAgeTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        animalHabitatTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        animalSpeciesTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        animalCostTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        animalGenderTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JToggleButton();
        lblAdditionalProperty = new javax.swing.JLabel();
        additionalTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JToggleButton();
        errorLbl = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add New Animal");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("type of animal");

        rdnBird.setText("Bird");
        rdnBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnBirdActionPerformed(evt);
            }
        });

        rdnFish.setText("Fish");
        rdnFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnFishActionPerformed(evt);
            }
        });

        jLabel3.setText("name");

        jLabel4.setText("age");

        jLabel5.setText("habitat");

        jLabel6.setText("secies");

        jLabel7.setText("cost (£)");

        jLabel9.setText("gender");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        lblAdditionalProperty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        errorLbl.setMaximumSize(new java.awt.Dimension(135, 16));
        errorLbl.setMinimumSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(backBtn)
                                                .addGap(92, 92, 92))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2))
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblAdditionalProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdnBird)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdnFish))
                                        .addComponent(animalNameTxt)
                                        .addComponent(animalAgeTxt)
                                        .addComponent(animalHabitatTxt)
                                        .addComponent(animalSpeciesTxt)
                                        .addComponent(animalGenderTxt)
                                        .addComponent(animalCostTxt)
                                        .addComponent(additionalTxt))
                                    .addComponent(clearBtn))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(addBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdnBird)
                            .addComponent(rdnFish))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(animalNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(animalAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animalHabitatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(animalSpeciesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(animalGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(animalCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(additionalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdditionalProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addBtn)
                    .addComponent(clearBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        AnimalMenu animalMenu = new AnimalMenu(loggedInAdmin);
        this.dispose();
        animalMenu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void rdnBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnBirdActionPerformed
        lblAdditionalProperty.setVisible(true);
        additionalTxt.setVisible(true);
        lblAdditionalProperty.setText("can it fly");
    }//GEN-LAST:event_rdnBirdActionPerformed

    private void rdnFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnFishActionPerformed
        lblAdditionalProperty.setVisible(true);
        additionalTxt.setVisible(true);
        lblAdditionalProperty.setText("water type");
    }//GEN-LAST:event_rdnFishActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        bg.clearSelection();
        animalNameTxt.setText("");
        animalGenderTxt.setText("");
        animalSpeciesTxt.setText("");
        animalAgeTxt.setText("");
        animalCostTxt.setText("");
        additionalTxt.setText("");
        animalHabitatTxt.setText("");
        lblAdditionalProperty.setVisible(false);
        additionalTxt.setVisible(false);
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String name = animalNameTxt.getText();
        String age = animalAgeTxt.getText();
        String cost = animalCostTxt.getText();
        String gender = animalGenderTxt.getText();
        String species = animalSpeciesTxt.getText();
        String additional = additionalTxt.getText();
        String habitat = animalHabitatTxt.getText();
        
        if(!rdnBird.isSelected() && !rdnFish.isSelected())
        {
            errorLbl.setText("Error: Please select a type of animal");
        }
        else if(name.equals("") || age.equals("") || cost.equals("") || gender.equals("") || species.equals("") || additional.equals("") || habitat.equals(""))
        {
            errorLbl.setText("Error: Please complete ALL fields");
        }
        else{
            try
            {
                int intAge = Integer.parseInt(age);
                try
                {
                    double doubleCost = Double.parseDouble(cost);
                    if(gender.length() != 1)
                    {
                        errorLbl.setText("Error: Please enter M or F for gender");
                    }
                    else
                    {
                        char charGender = gender.charAt(0);
                        if(rdnBird.isSelected())
                        {
                            if(additional.equalsIgnoreCase("True"))
                            {
                                boolean canFly = true;
                                
                                //(String nameIn, String typeIn, int ageIn, String habitatIn, double costIn, boolean isAvailableIn, char genderIn, boolean canFlyIn){
                                Bird bird = new Bird(name, species, intAge, habitat, doubleCost, true, charGender, canFly);
                                DBManager db = new DBManager();
                                db.addAnimal(bird);
                                
                                errorLbl.setText("New Bird added");
                            }
                        
                        else if(additional.equalsIgnoreCase("False"))
                        {
                            boolean canFly = false;
                            Bird bird = new Bird(name, species, intAge, habitat, doubleCost, true, charGender, canFly);
                            DBManager db = new DBManager();
                            db.addAnimal(bird);
                            
                            errorLbl.setText("New Bird added");
                        }
                        else
                        {
                            errorLbl.setText("Error: Enter true/false ONLY");
                        }
                    }
                    
                    else
                        {
                         //(String nameIn, String typeIn, int ageIn, String habitatIn, double costIn, boolean isAvailableIn, char genderIn, String waterTypeIn){
                         Fish fish = new Fish(name, species, intAge, habitat, doubleCost, true, charGender, additional);
                         DBManager db = new DBManager();
                         db.addAnimal(fish);
                         
                         errorLbl.setText("New Fish added");
                    }
                }
                }
                catch(Exception ex)
                {
                    errorLbl.setText("Error: Please enter numbers only for cost");
                }
            }
            catch(Exception ex)
            {
                errorLbl.setText("Error: Please enter a number only for age");
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBtn;
    private javax.swing.JTextField additionalTxt;
    private javax.swing.JTextField animalAgeTxt;
    private javax.swing.JTextField animalCostTxt;
    private javax.swing.JTextField animalGenderTxt;
    private javax.swing.JTextField animalHabitatTxt;
    private javax.swing.JTextField animalNameTxt;
    private javax.swing.JTextField animalSpeciesTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JToggleButton clearBtn;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAdditionalProperty;
    private javax.swing.JRadioButton rdnBird;
    private javax.swing.JRadioButton rdnFish;
    // End of variables declaration//GEN-END:variables
}
